version: '3.8'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
       - '6379:6379'
    expose:
      - 6379
  database:
    image: mongo:latest
    hostname: mongo
    ports:
      - '27017:27017'
    expose:
      - 27017
#    command: mongod